contacts_manager/urls.py
from django.urls import path, re_path
from . import views
# from .views import ContactView

app_name = 'contacts_manager'
urlpatterns = [
    path('<int:profile_id>/contact/create', views.create_contact, name='create_contact'),
    path('<int:profile_id>/contact/view/<int:contact_id>', views.view_contact, name='view_contact'),
    re_path(r'^(?P<profile_id>\d+)/contact/save/(?P<contact_id>\d{0,3})$', views.save_contact, name='save_contact'),
    path('<int:profile_id>/contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
]

crm_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('profile/', include('profile_manager.urls', namespace='profile_manager')),
    path('profile/', include('contacts_manager.urls', namespace='contacts_manager')),
    path('auth/', include('auth_manager.urls', namespace='auth_manager')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
]

contacts_manager/models.py
from django.db import models


class Contact(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Contact: {self.first_name} {self.last_name} {self.email}"

contacts_manager/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        # Set required fields
        self.fields['last_name'].required = True
        self.fields['first_name'].required = True
        self.fields['email'].required = True
        # Set optional fields (remove 'required' attribute)
        self.fields['phone'].required = False
        # TODO What if the user wants to change his\her user name?

contacts_manager/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ContactForm
from profile_manager.models import Profile


def create_contact(request, profile_id):
    template = 'contacts_manager/contact_form.html'
    profile = Profile.objects.get(id=profile_id)
    form = ContactForm()
    context = {
        'profile': profile,
        'form': form,
    }

    return render(request, template, context)


def view_contact(request, profile_id, contact_id):
    template = 'contacts_manager/contact_form.html'
    profile = Profile.objects.get(id=profile_id)
    contact = profile.contacts.get(id=contact_id)
    form = ContactForm(request.POST or None, instance=contact)
    context = {
        'profile': profile,
        'contact': contact,
        'form': form,
    }

    return render(request, template, context)


def save_contact(request, profile_id, contact_id=None):
    template = 'contacts_manager/contact_form.html'
    profile = Profile.objects.get(id=profile_id)
    contact = None
    msg = "Contact created successfully."

    if contact_id is not None and contact_id != '':
        contact = profile.contacts.get(id=contact_id)
        msg = "Changes saved successfully."

    context = {
        'profile': profile,
        'contact': contact,
    }

    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            profile.contacts.add(form.instance)
            messages.success(request, msg)
        else:
            context['form'] = form

    return render(request, template, context)


def delete_contact(request, profile_id, contact_id):
    profile = Profile.objects.get(id=profile_id)
    # TODO: Error handling here
    contact = profile.contacts.get(id=contact_id)
    contact.delete()
    messages.success(request, 'Contact was deleted successfully.')
    return redirect(f"/profile/{profile_id}")

templates/contacts_manager/contact_form.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            <strong>Error!</strong> There are errors in the form.
        </div>
    {% endif %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="post"
          class="post-form"
          action="{% url 'contacts_manager:save_contact' profile_id=profile.id contact_id=contact.id %}"
    >

        {% csrf_token %}
        <div class="mb-3">
            {% if form.errors.last_name %}
                <div class="text-danger">{{ form.errors.last_name.0 }}</div>
            {% endif %}
          <label for="in_last_name" class="form-label">Last Name</label>
          <input type="text" class="form-control" id="in_last_name"
                 name="last_name"
                 placeholder="Last Name"
                 value="{{ contact.last_name }}"
          >
        </div>
        <div class="mb-3">
            {% if form.errors.first_name %}
                <div class="text-danger">{{ form.errors.first_name.0 }}</div>
            {% endif %}
          <label for="in_first_name" class="form-label">First Name</label>
          <input type="text" class="form-control"
                 id="in_first_name"
                 name="first_name"
                 placeholder="First Name"
                 value="{{ contact.first_name }}"
          >
        </div>
        <div class="mb-3">
            {% if form.errors.email %}
                <div class="text-danger">{{ form.errors.email.0 }}</div>
            {% endif %}
          <label for="exampleFormControlInput1" class="form-label">Email address</label>
          <input type="email" class="form-control"
                 id="exampleFormControlInput1"
                 name="email"
                 placeholder="name@example.com"
                 value="{{ contact.email }}"
          >
        </div>
        <div class="mb-3">
          <label for="in_phone_number" class="form-label">Phone Number</label>
          <input type="text" class="form-control"
                 id="in_phone_number"
                 name="phone"
                 placeholder="Phone Number"
                 value="{{ contact.phone }}"
          >
        </div>

        <a class="btn btn-danger" href="{% url 'contacts_manager:delete_contact' profile_id=profile.id contact_id=contact.id %}"
           role="button">Delete Contact</a>
        <button type="submit" class="btn btn-primary mb-3">
            {% if contact.id %}Update{% else %}Create{% endif %} Contact
        </button>

    </form>
{% endblock %}

templates/contacts_manager/contacts_list.html
{% load custom_filters %}
  <table class="table table-hover">
    <thead>
    <tr>
      {% for field_name in fields %}
        <th>{{ field_name }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for profile in contacts %}
      <tr>
        {% for field_name in fields %}
          <td>{{ profile|getattribute:field_name }}</td>
        {% endfor %}
        <td><span class="material-symbols-outlined">edit</span></td>
        <td><span class="material-symbols-outlined">add</span></td>
      </tr>
    {% endfor %}
  </tbody>
  </table>