contacts_manager/urls.py
from django.urls import path, re_path
from . import views
# from .views import ContactView

app_name = 'contacts_manager'
urlpatterns = [
    path('<int:profile_id>/contact/create', views.create_contact, name='create_contact'),
    path('<int:profile_id>/contact/view/<int:contact_id>', views.view_contact, name='view_contact'),
    re_path(r'^(?P<profile_id>\d+)/contact/save/(?P<contact_id>\d{0,3})$', views.save_contact, name='save_contact'),
    path('<int:profile_id>/contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
]

crm_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('profile/', include('profile_manager.urls', namespace='profile_manager')),
    path('profile/', include('contacts_manager.urls', namespace='contacts_manager')),
    path('auth/', include('auth_manager.urls', namespace='auth_manager')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home'),
]

profile_manager/urls.py
from django.urls import path, re_path
from . import views
# from .views import ProfileView

app_name = 'profile_manager'
urlpatterns = [
    # TODO replace id parameter with @username/
    # path('<int:user_id>', views.view_profile, name='view_profile'),
    path('', views.view_profile, name='view_profile'),
    # path('<int:profile_id>', views.save_profile, name='save_profile'),
    re_path(r'^(?P<profile_id>\d{1,3})?$', views.save_profile, name='save_profile'),
    path('<int:profile_id>', views.delete_profile, name='delete_profile'),
]

profile_manager/models.py
from django.db import models
from django.contrib.auth.models import User

from contacts_manager.models import Contact


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True)
    address = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, null=True, blank=True)
    contacts = models.ManyToManyField(Contact, blank=True, null=True, related_name='profile')

    def __str__(self):
        return f"Profile: {self.first_name} {self.last_name}"

profile_manager/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'contacts']
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        # Set required fields
        self.fields['last_name'].required = True
        self.fields['first_name'].required = True
        self.fields['email'].required = True
        # Set optional fields (remove 'required' attribute)
        self.fields['phone'].required = False
        self.fields['address'].required = False


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, *kwargs)

        self.fields['username'].required = True
        self.fields['password'].required = True
        self.fields['last_name'].required = False
        self.fields['email'].required = False

profile_manager/views.py
from django.contrib import messages
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .forms import ProfileForm
from .models import Profile


# Create your views here.
def view_profile(request):
    template = 'profile_manager/profile_form.html'
    user_id = request.session['user_id']
    email = request.session['email']
    last_name = request.session['last_name']
    print(f'User ID: {user_id} --- Email: {email} Last Name: {last_name}')

    try:
        # profile = Profile.objects.get(user_id=user_id, email=email, last_name=last_name)
        profile = get_object_or_404(Profile, user_id=user_id, email=email, last_name=last_name)
        print(f'Profile String: {profile.__str__()}')
    except Http404:
        profile = Profile(user_id=user_id, last_name=last_name, email=email)
        print(f'Profile not found. Creating one.')

    form = ProfileForm(request.POST or None, instance=profile)
    context = {
        'profile': profile,
        'form': form,
    }

    return render(request, template, context)


def save_profile(request, profile_id=None):
    template = 'profile_manager/profile_form.html'
    profile = None
    msg = "Profile created successfully."

    if profile_id is not None and profile_id != '':
        profile = Profile.objects.get(id=profile_id)
        msg = "Changes saved successfully."

    context = {
        'profile': profile,
    }

    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, msg)

            # Update associated User email if changed
            user = profile.user
            if user.email != profile.email:
                user.email = profile.email
                user.save()
        else:
            print(f'{form.errors}')
            context['form'] = form

    return render(request, template, context)


def delete_profile(request, profile_id):
    return HttpResponse("Delete profile view.")

templates/profile_manager/profile_form.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            <strong>Error!</strong> There are errors in the form.
        </div>
    {% endif %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="post"
          class="post-form"
          action="{% url 'profile_manager:save_profile' profile_id=profile.id %}"
    >

        {% csrf_token %}
        <div class="mb-3">
            {% if form.errors.last_name %}
                <div class="text-danger">{{ form.errors.last_name.0 }}</div>
            {% endif %}
          <label for="in_last_name" class="form-label">Last Name</label>
          <input type="text" class="form-control" id="in_last_name"
                 name="last_name"
                 placeholder="Last Name"
                 value="{{ profile.last_name }}"
          >
        </div>
        <div class="mb-3">
            {% if form.errors.first_name %}
                <div class="text-danger">{{ form.errors.first_name.0 }}</div>
            {% endif %}
          <label for="in_first_name" class="form-label">First Name</label>
          <input type="text" class="form-control"
                 id="in_first_name"
                 name="first_name"
                 placeholder="First Name"
                 value="{{ profile.first_name }}"
          >
        </div>
        <div class="mb-3">
            {% if form.errors.email %}
                <div class="text-danger">{{ form.errors.email.0 }}</div>
            {% endif %}
          <label for="exampleFormControlInput1" class="form-label">Email address</label>
          <input type="email" class="form-control"
                 id="exampleFormControlInput1"
                 name="email"
                 placeholder="name@example.com"
                 value="{{ profile.email }}"
          >
        </div>
        <div class="mb-3">
            <label for="in_phone_number" class="form-label">Phone Number</label>
            <input type="text" class="form-control"
                   id="in_phone_number"
                   name="phone"
                   placeholder="Phone Number"
                   value="{{ profile.phone }}"
            >
        </div>
        <div class="mb-3">
            <label for="in_address" class="form-label">Address</label>
            <input type="text" class="form-control"
                   id="in_address"
                   name="address"
                   placeholder="Address"
                   value="{{ profile.address }}"
            >
        </div>

<!--        <a class="btn btn-danger"-->
<!--           href="{% url 'profile_manager:delete_profile' profile_id=profile.id  %}"-->
<!--           role="button">Delete Profile-->
<!--        </a>-->
        <button type="submit" class="btn btn-primary mb-3">
            {% if profile.id %}Update{% else %}Create{% endif %} Profile
        </button>

    </form>
{% endblock %}

templates/profile_manager/profile_view.html
{% extends 'base.html' %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <div id="profile_view">
    <h1>Profile View</h1>
    <p>{{ profile.last_name }}</p>
    <p>{{ profile.first_name }}</p>
  </div>

  {% load custom_filters %}
  <table class="table table-hover">
    <thead>
    <tr>
      {% for field_name in fields %}
        <th>{{ field_name }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for contact in contacts %}
      <tr>
        {% for field_name in fields %}
          <td>{{ contact|getattribute:field_name }}</td>
        {% endfor %}
        <td>
          <a href="{% url 'contacts_manager:view_contact' profile_id=profile.id contact_id=contact.id %}">
            <i class="fa-solid fa-pen-to-square"></i>
          </a>
        </td>
        <td>
          <a href="{% url 'contacts_manager:create_contact' profile_id=profile.id %}">
            <i class="fa-solid fa-plus"></i>
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
{% endblock %}